In [4]:
print(13 //2)

6


In [5]:
6**2


36

In [116]:
list_two =[*range(1,4)]
list_three =[*range(1,4)]
list_sum =[]
print(list_two)

for index in range(3):
    list_two[index]=list_two[index] ** 2
    list_three[index]=list_three[index] ** 3
    list_sum.append(list_two[index]+list_three[index])
print(list_sum)


[1, 2, 3]
[2, 12, 36]


In [118]:
import numpy as np
sample_array = np.array([1,2,3])
np.negative(sample_array)

array([-1, -2, -3])

In [119]:
np.exp(sample_array)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [120]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

In [122]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])

In [156]:
x = np.arange(2,7)
y =np.arange(3,8)
multi_array = np.array([x,y],dtype = np.int64)
print(multi_array)
print(multi_array.shape)
print(multi_array[1,2])
print(multi_array.dtype)
print(x[2:])
x = np.arange(18)
x=x.reshape(2,3,3)
x

[[2 3 4 5 6]
 [3 4 5 6 7]]
(2, 5)
5
int64
[4 5 6]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [157]:
x[1,1,1]

13

In [167]:
x[1,1:,1:3]

array([[13, 14],
       [16, 17]])

In [172]:
compare_opertation = x < 5
compare_opertation
x[x < 5]

array([0, 1, 2, 3, 4])

In [173]:
revelled_array = x.ravel()
revelled_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [175]:
revelled_array[2]=999999
x

array([[[     0,      1, 999999],
        [     3,      4,      5],
        [     6,      7,      8]],

       [[     9,     10,     11],
        [    12,     13,     14],
        [    15,     16,     17]]])

In [176]:
flattened_array = x.flatten()
flattened_array

array([     0,      1, 999999,      3,      4,      5,      6,      7,
            8,      9,     10,     11,     12,     13,     14,     15,
           16,     17])

In [178]:
flattened_array[2]=8888888
x

array([[[     0,      1, 999999],
        [     3,      4,      5],
        [     6,      7,      8]],

       [[     9,     10,     11],
        [    12,     13,     14],
        [    15,     16,     17]]])

In [179]:
print(x.transpose())

[[[     0      9]
  [     3     12]
  [     6     15]]

 [[     1     10]
  [     4     13]
  [     7     16]]

 [[999999     11]
  [     5     14]
  [     8     17]]]


In [181]:
x =np.arange(9)
x.shape=[3,3]
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [182]:
print(x.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [187]:
np.eye((6))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [188]:
mat_a =np.matrix([0,3,5,5,5,2]).reshape(2,3)

In [189]:
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [200]:
mat_b = np.matrix([3,4,3,-2,4,-2]).reshape(3,2)

In [196]:
product =mat_a * mat_b

In [197]:
product

matrix([[24, 42, 24],
        [17, 52, 17]])

In [201]:
product =np.matmul(mat_a,mat_b)

In [202]:
product

matrix([[ 29, -16],
        [ 38,   6]])

In [203]:
mat_a @ mat_b

matrix([[ 29, -16],
        [ 38,   6]])